### ISSUE TITLE
Speed comparison with OpenCV

### ISSUE THREAD

**Issue by hoebat** [smskelley/canny-opencl#27]
I'm looking at the benchmarking results with OpenCV and it seems that the OpenCV implementation is a lot faster. Do you know why this might be the case?

**Comment by smskelley** [comment]
It's been a while since I've worked on this, but I recall theorizing that it may be because OpenCV does not split up their segments into different kernels, so they incur less overhead. I never verified this, though, so it may be something else entirely or not representative of the full picture.

**Comment by hoebat** [comment]
they have it in three stages:

sobel
https://github.com/opencv/opencv/blob/master/modules/imgproc/src/canny.cpp#L227
https://github.com/opencv/opencv/blob/master/modules/imgproc/src/opencl/canny.cl#L119

hysterisis
https://github.com/opencv/opencv/blob/master/modules/imgproc/src/canny.cpp#L257
https://github.com/opencv/opencv/blob/master/modules/imgproc/src/opencl/canny.cl#L119

edges
https://github.com/opencv/opencv/blob/master/modules/imgproc/src/canny.cpp#L270
https://github.com/opencv/opencv/blob/master/modules/imgproc/src/opencl/canny.cl#L474

I'm still trying to figure out why it's so fast.
