### ISSUE TITLE
Linux version of this Project

### ISSUE THREAD

**Issue by r1w** [smskelley/canny-opencl#28]
Dear Sean Kelley
I am using your project for my resarch but when i am tring to make it in Ubuntu i face following error:
`/home/xx/Desktop/canny-opencl-master_OSX/src/live-capture/live-capture.cpp: In function ‘int main(int, char**)’:
/home/xx/Desktop/canny-opencl-master_OSX/src/live-capture/live-capture.cpp:24:3: error: ‘unique_ptr’ was not declared in this scope
   unique_ptr<ImageProcessor> processor(nullptr);
   ^~~~~~~~~~
/home/xxDesktop/canny-opencl-master_OSX/src/live-capture/live-capture.cpp:24:28: error: expected primary-expression before ‘>’ token
   unique_ptr<ImageProcessor> processor(nullptr);
                            ^
/home/xxDesktop/canny-opencl-master_OSX/src/live-capture/live-capture.cpp:24:30: error: ‘processor’ was not declared in this scope
   unique_ptr<ImageProcessor> processor(nullptr);
                              ^~~~~~~~~
/home/xx/Desktop/canny-opencl-master_OSX/src/live-capture/live-capture.cpp:24:30: note: suggested alternative: ‘glScissor’
   unique_ptr<ImageProcessor> processor(nullptr);
                              ^~~~~~~~~
                              glScissor
/home/xxDesktop/canny-opencl-master_OSX/src/live-capture/live-capture.cpp:54:5: error: ‘imshow’ was not declared in this scope
     imshow("canny", processor->output());
     ^~~~~~
/home/xx/Desktop/canny-opencl-master_OSX/src/live-capture/live-capture.cpp:54:5: note: suggested alternative:
In file included from /usr/include/opencv2/highgui/highgui.hpp:48:0,
                 from /home/xx/Desktop/canny-opencl-master_OSX/src/live-capture/live-capture.cpp:4:
/usr/include/opencv2/highgui.hpp:569:17: note:   ‘cv::imshow’
 CV_EXPORTS void imshow(const String& winname, const ogl::Texture2D& tex);
                 ^~~~~~
src/live-capture/CMakeFiles/live-capture.dir/build.make:62: recipe for target 'src/live-capture/CMakeFiles/live-capture.dir/live-capture.cpp.o' failed
make[2]: *** [src/live-capture/CMakeFiles/live-capture.dir/live-capture.cpp.o] Error 1
CMakeFiles/Makefile2:141: recipe for target 'src/live-capture/CMakeFiles/live-capture.dir/all' failed
make[1]: *** [src/live-capture/CMakeFiles/live-capture.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`
According to your comment, i would appreciate you if release Linux version of this project.

**Comment by jmespadero** [comment]
It is solved with PR #29 

Basically, you need to add the line

```c++
#include <memory>
```
to files src/live-capture/live-capture.cpp and src/benchmarking/benchmark.h
